---
apiVersion: v1
kind: ConfigMap
metadata:
  name: protobuf-schemas
data:
  your_schema.proto: |
    syntax = "proto3";
    package tutorial;
    import "google/protobuf/timestamp.proto";

    message Person {
      string name = 1;
      int32 id = 2;  // Unique ID number for this person.
      string email = 3;

      enum PhoneType {
        MOBILE = 0;
        HOME = 1;
        WORK = 2;
      }

      message PhoneNumber {
        string number = 1;
        PhoneType type = 2;
      }

      repeated PhoneNumber phones = 4;

      google.protobuf.Timestamp last_updated = 5;
    }

---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "protobuf-example"
spec:
  configuration:
    settings:
      format_schema_path: /opt/format_schemas/
    clusters:
      - name: cluster
        layout:
          shardsCount: 1
          replicasCount: 1

  defaults:
    templates:
      podTemplate: pod-template-with-volumes


  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:latest
              volumeMounts:
                - name: protobuf-schema-mount
                  mountPath: /opt/format_schemas/
          volumes:
            - name: protobuf-schema-mount
              configMap:
                name: protobuf-schemas
