name: run_tests
on: workflow_dispatch
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache python
        uses: actions/cache@v2
        id: cache-python
        with:
          path: ~/venv/qa
          key: python-${{ hashFiles('tests/image/requirements.txt') }}

      - name: Install python dependencies
        run: |
          set -x
          python3 -m venv ~/venv/qa
          ~/venv/qa/bin/pip3 install -U -r ./tests/image/requirements.txt
        if: |
          steps.cache-python.outputs.cache-hit != 'true'

      - name: Run Tests
        run: |
          set -x
          sudo ln -snvf ~/venv/qa/bin/tfs /bin/tfs
          ~/venv/qa/python3 ./tests/regression.py --only "/regression/e2e.test_operator/*" --log ./tests/raw.log
          ~/venv/qa/bin/tfs --debug --no-colors transform compact ./test/testflows/raw.log ./tests/compact.log
          ~/venv/qa/bin/tfs --debug --no-colors transform nice ./test/testflows/raw.log ./tests/nice.log.txt
          ~/venv/qa/bin/tfs --debug --no-colors transform short ./test/testflows/raw.log ./tests/short.log.txt
          ~/venv/qa/bin/tfs --debug --no-colors report results -a "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/" ./tests/raw.log - --confidential --copyright "Altinity LTD" --logo ./tests/altinity.png | ~/venv/qa/bin/tfs --debug --no-colors document convert > ./test/report.html

      - uses: actions/upload-artifact@v2
        with:
          name: testflows-logs
          path: |
            test/*.log
            test/*.log.txt
          if-no-files-found: error
          retention-days: 7

