name: run_tests
on: workflow_dispatch
jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get install -y conntrack
      - uses: medyagh/setup-minikube@master
        with:
          driver: none
          kubernetes-version: v1.21.9
      - run: |
          bash -xe ./deploy/prometheus/create-prometheus.sh
          bash -xe ./deploy/minio/install-minio-operator.sh
          bash -xe ./deploy/minio/install-minio-tenant.sh

          # bash -xe /deploy/grafana/grafana-with-grafana-operator/install-grafana-operator.sh
          # bash -xe /deploy/grafana/grafana-with-grafana-operator/install-grafana-with-operator.sh

          pip3 install -U -r ./tests/image/requirements.txt
          # docker-compose -f ./tests/docker-compose/docker-compose.yml pull runner
          # bash -xe ./tests/image/build_docker.sh
          python3 ./tests/regression.py --only "/regression/*" --native
          
